"""Unittest formatter - generates unittest test files"""

from typing import List
from pathlib import Path

from ..models import TestSuite, TestCase, TestType


class UnittestFormatter:
    """Formats test suites as unittest code"""

    def format_test_suite(self, test_suite: TestSuite) -> str:
        """Generate complete unittest test file"""
        lines = []

        # Header
        lines.append('"""')
        lines.append(f"Auto-generated tests for {test_suite.target}")
        lines.append("Generated by Test-Guardian")
        lines.append('"""')
        lines.append('')

        # Imports
        lines.append("import unittest")
        if test_suite.mocks:
            lines.append("from unittest.mock import Mock, patch")
        lines.append('')

        module_name = Path(test_suite.file_path).stem
        lines.append(f"from {module_name} import {test_suite.target}")
        lines.append('')

        # Test class
        class_name = f"Test{test_suite.target.replace('_', '').title()}"
        lines.append(f"class {class_name}(unittest.TestCase):")
        lines.append('    """Test cases for {}"'.format(test_suite.target))
        lines.append('')

        # Test methods
        for test_case in test_suite.test_cases:
            lines.extend(self._generate_test_method(test_case))
            lines.append('')

        # Main
        lines.append('')
        lines.append("if __name__ == '__main__':")
        lines.append("    unittest.main()")

        return '\n'.join(lines)

    def _generate_test_method(self, test_case: TestCase) -> List[str]:
        """Generate a single test method"""
        lines = []

        lines.append(f"    def {test_case.name}(self):")
        lines.append(f'        """{test_case.description}"""')

        # Arrange
        for inp in test_case.inputs:
            value_repr = repr(inp.value) if not isinstance(inp.value, str) else f'"{inp.value}"'
            lines.append(f"        {inp.name} = {value_repr}")

        # Act & Assert
        args = ", ".join(inp.name for inp in test_case.inputs)

        if test_case.test_type == TestType.ERROR:
            exception = test_case.expected_exception or "Exception"
            lines.append(f"        with self.assertRaises({exception}):")
            lines.append(f"            {test_case.function_name}({args})")
        else:
            lines.append(f"        result = {test_case.function_name}({args})")
            lines.append("        # TODO: Add assertion")
            lines.append("        self.assertIsNotNone(result)")

        return lines

    def save_test_file(self, test_suite: TestSuite, output_path: Path) -> None:
        """Save test suite to file"""
        code = self.format_test_suite(test_suite)

        with open(output_path, 'w') as f:
            f.write(code)
